name: Test Installing Qt

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - name: clone repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 1

    - name: Configure test project on windows
      if: startsWith(matrix.os, 'windows')
      run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          cd src
          qmake
          make
      
    - name: Configure test project on unix
      if: (!startsWith(matrix.os, 'windows'))
      run: |
          cd src
          qmake
          make
