name: Test Installing Qt

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

  
    - name: Configure test project on windows
      if: startsWith(matrix.os, 'windows')
      run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dir %Qt5_DIR%/lib/cmake
          dir
      shell: cmd
    - name: TestBuildWindows
      if: startsWith(matrix.os, 'windows')
      run: ls
      shell: cmd
      
    - name: Configure test project on unix
      if: (!startsWith(matrix.os, 'windows'))
      run: |
          ls $Qt5_DIR/lib/cmake
          dir
      shell: bash
    - name: TestBuildUnix
      if: (!startsWith(matrix.os, 'windows'))
      run: ls
      shell: cmd
